services:
  backend:
    image: rotmg-raid-backend:development
    build:
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    command: [ "dev-entrypoint", "sh", "-c", "npm run migrate && exec npm run dev" ]

  bot:
    image: rotmg-raid-bot:development
    build:
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./bot:/app
      - bot_node_modules:/app/node_modules
    command: [ "dev-entrypoint", "npm", "run", "dev" ]

volumes:
  backend_node_modules:
  bot_node_modules:
