# bot/Dockerfile.dev
FROM node:20-alpine

WORKDIR /app
ENV CI=true

COPY package*.json ./

RUN npm ci --no-audit --no-fund \
    && sha256sum package.json package-lock.json \
      | sha256sum \
      | cut -d ' ' -f 1 > node_modules/.package-manifests.sha256

COPY docker-entrypoint.dev.sh /usr/local/bin/dev-entrypoint
RUN chmod +x /usr/local/bin/dev-entrypoint

COPY tsconfig.json ./
COPY src ./src
